load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "gohelpers",
    srcs = [
        "helpers.go",
        "priorityqueue.go",
    ],
    importpath = "github.com/reusing-code/adventofcode/gohelpers",
    visibility = ["//visibility:public"],
)
