load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "image",
    srcs = [
        "image.go",
    ],
    importpath = "github.com/reusing-code/adventofcode/gohelpers/image",
    visibility = ["//visibility:public"],
)
